services:
    lukewcs.statspermissions.listener:
        class: lukewcs\statspermissions\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@auth'
            - '@user'
            - '@dispatcher'
        tags:
            - { name: event.listener }
    lukewcs.statspermissions.controller.acp:
        class: lukewcs\statspermissions\controller\acp_stats_permissions_controller
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@request'
            - '@ext.manager' 
