services:
    lukewcs.statspermissions.listener:
        class: lukewcs\statspermissions\event\listener
        arguments:
            - '@lukewcs.statspermissions.core'
        tags:
            - { name: event.listener }
    lukewcs.statspermissions.core:
        class: lukewcs\statspermissions\core\stats_permissions
        arguments:
            - '@config'
            - '@template'
            - '@auth'
            - '@user'
            - '@dispatcher'
            - '@language'
